/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
  * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/

#ifndef ROOUNIFPDF
#define ROOUNIFPDF

#include "RooAbsPdf.h"
#include "RooRealProxy.h"
#include "RooCategoryProxy.h"
#include "RooAbsReal.h"
#include "RooAbsCategory.h"
 
class RooUnifPdf : public RooAbsPdf {
public:
  RooUnifPdf() {} ; 
  RooUnifPdf(const char *name, const char *title,
	      RooAbsReal& _t,
	      RooAbsReal& _p,
	      RooAbsReal& _alpha,
	      RooAbsReal& _beta,
	      RooAbsReal& _gamma,
	      RooAbsReal& _scale);
  RooUnifPdf(const RooUnifPdf& other, const char* name=0) ;
  virtual TObject* clone(const char* newname) const { return new RooUnifPdf(*this,newname); }
  inline virtual ~RooUnifPdf() { }

protected:

  RooRealProxy t ;
  RooRealProxy p ;
  RooRealProxy alpha ;
  RooRealProxy beta ;
  RooRealProxy gamma ;
  RooRealProxy scale ;
  
  Double_t evaluate() const ;

private:

  ClassDef(RooUnifPdf,1) // Your description goes here...
};
 
#endif
